on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:

name: Launch Scala Steward
permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Launch Scala Steward
    steps:
      - name: Checkout repository so `repos.md` is available
        uses: actions/checkout@v4
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          repos-file: 'repos.md'